---
title: "Boris bikes"
output: html_notebook
---


```{r}
library(plyr)
library(dplyr)
library(magrittr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(knitr)
library(leaflet)
options(stringsAsFactors = FALSE)
load('journey_data.RData')
```

Create start and end aggregations.

```{r}
journeys_start <- journey_data %>% group_by(`StartStation Name`, startstation_long, startstation_lat) %>% 
  summarise(avg_duration = mean(Duration, na.rm = TRUE))
journeys_end <- journey_data %>% group_by(`EndStation Name`, endstation_long, endstation_lat) %>% 
  summarise(avg_duration = mean(Duration, na.rm = TRUE))
```

Create the interactive maps.

```{r}
leaflet(journeys_start) %>% addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(lng = ~startstation_long, lat = ~startstation_lat, 
                   radius = ~avg_duration/200, 
                   stroke = FALSE, fillColor = 'green',
                   fillOpacity = 0.6, group = 'Start Stations',
                   popup = ~paste0('<strong>',
                                   `StartStation Name`,'</strong><br />',
                                   avg_duration))
```

```{r}
leaflet(journeys_end) %>% addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(lng = ~endstation_long, lat = ~endstation_lat, 
                   radius = ~avg_duration/200, 
                   stroke = FALSE, fillColor = 'red',
                   fillOpacity = 0.6, group = 'End Stations',
                   popup = ~paste0('<strong>',
                                   `EndStation Name`,'</strong><br />',
                                   avg_duration))
```

Combination map
```{r}
journeys_total <- left_join(journeys_start %>% rename(start_avg_duration = avg_duration), journeys_end %>% rename(end_avg_duration = avg_duration), by = c('StartStation Name' = 'EndStation Name')) %>% rename(StationName = `StartStation Name`)

leaflet(journeys_total) %>% addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(lng = ~startstation_long, lat = ~startstation_lat, 
                   radius = ~start_avg_duration/200, 
                   stroke = FALSE, fillColor = 'green',
                   fillOpacity = 0.6, group = 'Start Stations',
                   popup = ~paste0('<strong>',
                                   `StationName`,'</strong><br />',
                                   start_avg_duration)) %>% 
  addCircleMarkers(lng = ~endstation_long, lat = ~endstation_lat, 
                   radius = ~end_avg_duration/200, 
                   stroke = FALSE, fillColor = 'red',
                   fillOpacity = 0.6, group = 'End Stations',
                   popup = ~paste0('<strong>',
                                   `StationName`,'</strong><br />',
                                   end_avg_duration)) %>% 
  addLayersControl(
    overlayGroups = c("Start Stations", "End Stations"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

Combination map
```{r}
leaflet() %>% addProviderTiles('CartoDB.Positron') %>% 
  addCircles(data = journeys_start,
                   lng = ~startstation_long, lat = ~startstation_lat, 
                   radius = ~avg_duration/5, 
                   stroke = FALSE, fillColor = 'green',
                   fillOpacity = 0.6, group = 'Start Stations',
                   popup = ~paste0('<strong>',
                                   `StartStation Name`,'</strong><br />',
                                   avg_duration)) %>%
  addCircles(data = journeys_end,
                   lng = ~endstation_long, lat = ~endstation_lat, 
                   radius = ~avg_duration/5, 
                   stroke = FALSE, fillColor = 'red',
                   fillOpacity = 0.6, group = 'End Stations',
                   popup = ~paste0('<strong>',
                                   `EndStation Name`,'</strong><br />',
                                   avg_duration)) %>% 
  addLayersControl(
    overlayGroups = c("Start Stations", "End Stations"),
    options = layersControlOptions(collapsed = FALSE)
  )
```